name: Cirq Compatibility

on:
  push:
    branches:
      - joint-cutting  # Trigger on push to joint-cutting
  workflow_dispatch:  

jobs:
  consistency:
    name: Cirq Compatibility
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libblas-dev liblapack-dev
      - name: Install xtl (dependency for xtensor)
        run: |
          git clone https://github.com/xtensor-stack/xtl.git
          cd xtl
          cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install
      - name: Install xtensor
        run: |
          git clone https://github.com/xtensor-stack/xtensor.git
          cd xtensor
          cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install
      - name: Install xtensor-blas
        run: |
          git clone https://github.com/xtensor-stack/xtensor-blas.git
          cd xtensor-blas
          cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install

      - name: Install Cirq 
        run: pip3 install --upgrade cirq~=1.0.dev
      
      - name: Install qsim requirements
        run: pip3 install -r requirements.txt
      
      - name: Install test requirements
        run: pip3 install -r dev-requirements.txt
      
      - name: Run python tests
        env:
          CXXFLAGS: "-I/usr/local/include"
          LDFLAGS: "-L/usr/local/lib"
          LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
        run: make run-py-tests
